[project]
name = "immrax"
version = "0.3.7b1"
description = "Fast, guaranteed reachable set over-approximation using interval analysis"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.11"

dependencies = [
    "diffrax>=0.7.0",
    "equinox>=0.12.2",
    "immutabledict>=4.2.0",
    "jax>=0.6.1",
    "jaxtyping>=0.2.33",
    "linrax~=0.3.0",
    "matplotlib~=3.9.2",
    "pypoman~=1.1.0",
    "shapely~=2.0.6",
    "tabulate~=0.9.0",
]

[project.urls]
"Homepage" = "https://github.com/gtfactslab/immrax"
"Documentation" = "https://immrax.readthedocs.io"
"Bug Tracker" = "https://github.com/gtfactslab/immrax/issues"
"Source Code" = "https://github.com/gtfactslab/immrax"

[project.optional-dependencies]
cuda12 = [
    "jax[cuda12]>=0.6.1",
]
cuda13 = [
    "jax[cuda13]>=0.7.0",
]
examples = [
    "casadi~=3.6.7",
    "control~=0.10.1",
    "ipykernel~=6.29.5",
    "ipympl~=0.9.7",
]

[tool.uv]
conflicts = [
    [
        {extra = "cuda12"},
        {extra = "cuda13"},
    ],
]

[dependency-groups]
dev = [
    "pytest>=9.1.0",
    "ruff>=0.15.17",
    "twine>=6.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pytest.ini_options]
pythonpath = ["."]

[tool.ruff]

[tool.ruff.lint]

ignore = [
	"E731", # We like lambda functions
	"F722", # jaxtyping dimension annotations
]
